=== BackupTheBerlios/springbreak/sena/SimulatorStuff/xsd/EventType.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 sp1 U (http://www.xmlspy.com) by - (Ru-Board) -->
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by - (-) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="virtualRoot">
		<xs:choice>
			<xs:element ref="EventType"/>
			<xs:element ref="EventObjectType"/>
			<xs:element ref="VirtualEventType"/>
		</xs:choice>
	</xs:complexType>
	<xs:element name="EventType" type="EventTypeType"/>
	<xs:element name="EventObjectType" type="EventObjectTypeType"/>
	<xs:complexType name="EventTypeAttributeType">
		<xs:sequence>
			<xs:element name="DataType" type="EventDataTypeType"/>
			<xs:element name="Validators" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Validator" type="EventTypeAttributeValidatorType" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="catalogName" type="xs:string" use="required"/>
		<xs:attribute name="reuseable" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="EventDataTypeType">
		<xs:sequence>
			<xs:element name="RuntimeType" nillable="true">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="catalogName" type="xs:string" use="optional"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="catalogName" type="xs:string" use="required"/>
		<xs:attribute name="multiValue" type="xs:boolean" use="required"/>
	</xs:complexType>
	<xs:complexType name="EventTypeAttributeValidatorType">
		<xs:sequence>
			<xs:element name="Parameters" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Parameter" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="name" type="xs:string" use="required"/>
										<xs:attribute name="runtimeType" type="xs:string" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="catalogName" type="xs:string" use="required"/>
		<xs:attribute name="runtimeType" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="EventObjectTypeType">
		<xs:sequence>
			<xs:element name="Attributes" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Attribute" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="EventTypeAttributeType">
										<xs:sequence>
											<xs:element name="Name" type="xs:string"/>
											<xs:element name="Mandatory" type="xs:boolean"/>
											<xs:choice minOccurs="0">
												<xs:element name="DefaultValue" type="xs:string"/>
												<xs:element name="DefaultValues">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="Value" type="xs:string" maxOccurs="unbounded"/>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:sequence>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="catalogName" type="xs:NMTOKEN" use="required"/>
	</xs:complexType>
	<xs:element name="EventTypeAttribute" type="EventTypeAttributeType"/>
	<xs:element name="EventDataType" type="EventDataTypeType"/>
	<xs:element name="EventTypeAttributeValidator" type="EventTypeAttributeValidatorType"/>
	<xs:element name="VirtualEventType" type="VirtualEventTypeType"/>
	<xs:complexType name="VirtualEventTypeType">
		<xs:complexContent>
			<xs:extension base="EventObjectTypeType">
				<xs:sequence>
					<xs:element name="BaseTypes" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="BaseType" type="xs:string" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="XPathConstraints" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Expression" type="xs:string" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EventTypeType">
		<xs:complexContent>
			<xs:extension base="EventObjectTypeType">
				<xs:sequence>
					<xs:element name="AllowUnknownAttributes" type="xs:boolean"/>
					<xs:element name="ImplementationType" type="xs:string"/>
					<xs:element name="Parent" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== BackupTheBerlios/springbreak/sena/SimulatorStuff/definitions/ShipmentExpeditedEventType.xml
<?xml version="1.0" encoding="utf-8"?>
<EventType catalogName="ShipmentExpedited" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="OrderId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>OrderId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="TransportId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>TransportIdFailed</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="true" catalogName="Transport">
			<DataType multiValue="false" catalogName="TransportInfo">
				<RuntimeType catalogName="TransportInfo"/>
			</DataType>
			<Name>Transport</Name>
			<Mandatory>false</Mandatory>
		</Attribute>
	</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/generic/eventDefinitions/ShipmentTenderAcceptedEventType.xml
<?xml version="1.0" encoding="utf-8"?>
<EventType catalogName="ShipmentTenderAccepted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="OrderId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>OrderId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="CarrierId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>CarrierId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
	</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/sena/SimulatorStuff/Telco/definitions/VisitsWebpageEventType.xml
<?xml version="1.0" encoding="UTF-8"?>
<EventType catalogName="VisitsWebpage" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="UserId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>UserId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="true" catalogName="WebInfo">
			<DataType multiValue="false" catalogName="WebInfo">
				<RuntimeType catalogName="WebInfo"/>
			</DataType>
			<Name>WebInfo</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/sena/SimulatorStuff/Telco/definitions/RequestMobilePhone_DownloadEventType.xml
<?xml version="1.0" encoding="UTF-8"?>
<EventType catalogName="RequestMobilePhone_Download" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="CustomerId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>CustomerId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="ContentId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>ContentId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="false" catalogName="Connection">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>Connection</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="false" catalogName="ContentType">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>ContentType</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
	</Attributes>
		
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/generic/eventDefinitions/ShipmentTenderIssuedEventType.xml
<?xml version="1.0" encoding="utf-8"?>
<EventType catalogName="ShipmentTenderIssued" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="OrderId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>OrderId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DeliveryDate">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DeliveryDate</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="true" catalogName="FurtherInfo">
			<DataType multiValue="false" catalogName="ShipmentInfo">
				<RuntimeType catalogName="ShipmentInfo"/>
			</DataType>
			<Name>FurtherInfo</Name>
			<Mandatory>false</Mandatory>
		</Attribute>
	</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/sena/SimulatorStuff/Telco/definitions/OutgoingVideoCallEventType.xml
<?xml version="1.0" encoding="UTF-8"?>
<EventType catalogName="OutgoingVideoCall" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="CustomerId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>CustomerId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="true" catalogName="CalleeNr">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>CalleeNr</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="true" catalogName="Duration">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.Int32</RuntimeType>
			</DataType>
			<Name>Duration</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="true" catalogName="Location">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>Location</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/sena/SimulatorStuff/Telco/definitions/BillPaidEventType.xml
<?xml version="1.0" encoding="UTF-8"?>
<EventType catalogName="BillPaid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="UserId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>UserId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="false" catalogName="BillId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>BillId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
error(3): wrong syntax
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>

		</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>

=== BackupTheBerlios/springbreak/sena/SimulatorStuff/Telco/definitions/BillSentEventType.xml
<?xml version="1.0" encoding="UTF-8"?>
<EventType catalogName="BillSent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\xsd\EventType.xsd">
	<Attributes>
		<Attribute reuseable="false" catalogName="UserId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>UserId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="BillId">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>BillId</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		<Attribute reuseable="false" catalogName="DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="false" catalogName="Sum">
			<DataType multiValue="false" catalogName="String">
				<RuntimeType>System.String</RuntimeType>
			</DataType>
			<Name>Sum</Name>
			<Mandatory>true</Mandatory>
		</Attribute>
		
		<Attribute reuseable="false" catalogName="Until_DateTime">
			<DataType multiValue="false" catalogName="DateTime">
				<RuntimeType>System.DateTime</RuntimeType>
			</DataType>
			<Name>Until_DateTime</Name>
			<Mandatory>true</Mandatory>
		</Attribute>

		</Attributes>
	<AllowUnknownAttributes>false</AllowUnknownAttributes>
	<ImplementationType>Eventis.Core.Event.BaseEvent</ImplementationType>
</EventType>
